require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "bin/**/*"
    - "db/schema.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Rails/Date:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false
