# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PgQuery::String`.
# Please instead update this file by running `bin/tapioca dsl PgQuery::String`.

class PgQuery::String
  sig { params(sval: T.nilable(String)).void }
  def initialize(sval: nil); end

  sig { void }
  def clear_sval; end

  sig { returns(String) }
  def sval; end

  sig { params(value: String).void }
  def sval=(value); end
end
