# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Spring; end
module Pagy::BootstrapExtra; end
module Pagy::FrontendHelpers::Frontend; end
module Pagy::SupportExtra; end
